name: Build Artifacts

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    uses: ./.github/workflows/tests.yml

  check-version:
    uses: ./.github/workflows/versioncheck.yml

  confirm-version:
    needs: [check-version]
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ needs.check-version.outputs.unreleased }}"

  build:
    strategy:
      matrix:
        os: [mac-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    needs: [run-tests, check-version]
    if: needs.check-version.outputs.unreleased == 'true'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - if: matrix.os == 'mac-latest'
        uses: ./.github/workflows/mac_keychain.yml
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - run: npm ci
      - run: npm run build:desktop
      - run: npm run pack -w app/desktop
