name: Check if Version is Released

on:
  workflow_call:
    outputs:
      unreleased:
        value: ${{ jobs.check-version.outputs.unreleased }}

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      unreleased: ${{ steps.release-info.outputs.result }}
    steps:
      - uses: actions/checkout@v3
      - name: Get current package version
        id: version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: app/desktop
      - name: Get release information
        id: release-info
        env:
          version: ${{ steps.version.outputs.current-version }}
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const response = await github.rest.repos.listReleases(
                { owner: "mindofmatthew", repo: "text.management" }
              );

              console.log(JSON.stringify(response, null, 2));

              return false;
            } catch (e) {
              if (e.status === 404) {
                return false;
              }
              throw e;
            }
      - if: ${{ ! steps.release-info.outputs.result }}
        run: echo "No draft release exists, skipping build step"
