name: Check if Version is Released

on: workflow_call

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      unreleased: contains(fromJSON('[null, true]'), steps.release.outputs.draft)
    steps:
      - uses: actions/checkout@v3
      - name: Get current package version
        id: version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: app/desktop
      - name: Get release information
        id: release-info
        env:
          version: ${{ steps.version.outputs.result }}
        uses: actions/github-script@v3
          with:
            script: |
              try {
                const { data } = await github.rest.repos.getReleaseByTag(
                  { "mindofmatthew", "text.management", process.env.version }
                );
                return data.draft;
              } catch (e) {
                if (e.status === 404) {
                  return true;
                }
                throw e;
              }
      - id: release
        run: echo "draft=${{ fromJSON(steps.release-info.outputs.data).draft }}" >> $GITHUB_OUTPUT
